openai:
  api_key: $OPENAI_API_KEY
  chat_model: "gpt-3.5-turbo"
  temperature: 0.0
  max_tokens: 256
  embedding_model: "text-embedding-ada-002"


pinecone:
  api_key: $PINECONE_API_KEY
  environment: $PINECONE_ENVIRONMENT

prompts:
  chat:
    filepath: "./src/prompts/chat/system.txt"

  functions:
    filepath: "./src/prompts/functions/signatures.json"

<<<<<<< HEAD
huggingface:
  api_key: $HUGGINGFACE_API_KEY
  embedding_model: "intfloat/multilingual-e5-small"
=======
>>>>>>> 40731b41b3bfe5317ad9c6b9b89eb31a1ced9642

